export const CREATECOURSECATEGORY_REQUEST = "CREATECOURSECATEGORY_REQUEST";
export const CREATECOURSECATEGORY_SUCCESS = "CREATECOURSECATEGORY_SUCCESS";
export const CREATECOURSECATEGORY_FAIL = "CREATECOURSECATEGORY_FAIL";


export const ALLCOURSECATEGORY_REQUEST = "ALLCOURSECATEGORY_REQUEST";
export const ALLCOURSECATEGORY_SUCCESS = "ALLCOURSECATEGORY_SUCCESS";
export const ALLCOURSECATEGORY_FAIL = "ALLCOURSECATEGORY_FAIL";

export const DELETECOURSECATEGORY_REQUEST = "DELETECOURSECATEGORY_REQUEST";
export const DELETECOURSECATEGORY_SUCCESS = "DELETECOURSECATEGORY_SUCCESS";
export const DELETECOURSECATEGORY_FAIL = "DELETECOURSECATEGORY_FAIL";



export const GET_COURSECATEGORY_REQUEST = "GET_COURSECATEGORY_REQUEST";
export const GET_COURSECATEGORY_SUCCESS = "GET_COURSECATEGORY_SUCCESS";
export const GET_COURSECATEGORY_FAIL = "GET_COURSECATEGORY_FAIL";


export const UPDATE_COURSECATEGORY_REQUEST = "UPDATE_COURSECATEGORY_REQUEST";
export const UPDATE_COURSECATEGORY_SUCCESS = "UPDATE_COURSECATEGORY_SUCCESS";
export const UPDATE_COURSECATEGORY_FAIL = "UPDATE_COURSECATEGORY_FAIL";