export const CREATE_REQUEST = "CREATE_REQUEST";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAIL = "CREATE_FAIL";


export const STUDENT_REQUEST = "STUDENT_REQUEST";
export const STUDENT_SUCCESS = "STUDENT_SUCCESS";
export const STUDENT_FAIL = "STUDENT_FAIL";

export const SINGLE_VIEW_REQUEST = "SINGLE_VIEW_REQUEST";
export const SINGLE_VIEW_SUCCESS = "SINGLE_VIEW_SUCCESS";
export const SINGLE_VIEW_FAIL = "SINGLE_VIEW_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const NEW_COURSE_REQUEST = "NEW_COURSE_REQUEST";
export const NEW_COURSE_SUCCESS = "NEW_COURSE_SUCCESS";
export const NEW_COURSE_FAIL = "NEW_COURSE_FAIL";

export const ALLSTUDENT_COURSE_REQUEST = "ALLSTUDENT_COURSE_REQUEST";
export const ALLSTUDENT_COURSE_SUCCESS = "ALLSTUDENT_COURSE_SUCCESS";
export const ALLSTUDENT_COURSE_FAIL = "ALLSTUDENT_COURSE_FAIL";

export const NEW_COURSE_DELETE_REQUEST = "NEW_COURSE_DELETE_REQUEST";
export const NEW_COURSE_DELETE_SUCCESS = "NEW_COURSE_DELETE_SUCCESS";
export const NEW_COURSE_DELETE_FAIL = "NEW_COURSE_DELETE_FAIL";